# Generated by Django 4.1.1 on 2023-05-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
